language: java

jdk:
- openjdk8
- openjdk11

before_install:
  - >
    openssl aes-256-cbc -K $encrypted_1da62148018a_key -iv $encrypted_1da62148018a_iv \
      -in src/main/resources/build-key.gpg.enc -out build-key.gpg -d

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn -s src/test/resources/settings.xml -q package -Dmaven.test.skip -Dmaven.javadoc.skip -B -V

script:
  - mvn -s src/test/resources/settings.xml -q help:active-profiles verify

after_success:
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is main; all other builds are done on PRs to main
branches:
  only:
  - main

notifications:
  pushover:
    api_key: "${PUSHOVER_API_KEY}"
    users:
      - "${PUSHOVER_USER_KEY}"
    template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"
    on_success: never
    on_failure: change

sudo: false
