language: java

jdk:
- openjdk8
- openjdk11

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn -s src/test/resources/settings.xml -q package -Dmaven.test.skip -Dmaven.javadoc.skip -B -V

script:
  - mvn -s src/test/resources/settings.xml -q help:active-profiles verify

after_success:
  - mvn -s src/test/resources/settings.xml site -Djava.util.logging.config.file=src/test/resources/logging.properties site:deploy
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/get_build_key $encrypted_0e0f91f7a6ed_key $encrypted_0e0f91f7a6ed_iv
  - src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is master; all other builds are done on PRs to master
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

sudo: false
