#! /bin/bash

#
# Gets the next stable version from a Maven snapshot project.
#

VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='0.8.10-SNAPSHOT' --non-recursive exec:exec)
PROJECT=$(mvn -q -Dexec.executable="echo" -Dexec.args='freelib-utils' --non-recursive exec:exec)

echo $PROJECT-${VERSION%"-SNAPSHOT"}
